name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate pacman graph
        uses: maurodesouza/profile-readme-stats@v1
        with:
          username: YOUR_GITHUB_USERNAME

      - name: Push generated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generate pacman graph"
          git push
